# 변수

print() -> 출력, type() -> type return

In [1]:
a = 1; print(type(a))

<class 'int'>


변수형 float

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


int() -> int로 바꿔서 return, 1.2 -> 1

In [4]:
a = 1.2; a = int(a); print(type(a)); print(a)

<class 'int'>
1


b가 string으로 숫자로만 이뤄져 있으면 int() 나 float로 타입변환이 가능하다.

In [15]:
a = 'abc'; print(type(a)); print(a[1])
b = '123'; print(type(b)); print(b[1]); print(float(b));

<class 'str'>
b
<class 'str'>
2
123.0


# list 함수

list() 안에 str을 넣으면 글자하나하나를 list의 원소로 만든다

In [16]:
a = 'a123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['a', '1', '2', '3']
2


list의 원소로 list도 가능하다.

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


tuple -> () , list -> []

In [19]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


# Dictionary

:로 key 와 value의 pair 생성, key를 index처럼 사용해 value 값을 찾을 수 있다

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [21]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

# Numpy

numpy라는 packege import, numpy를 import를 통해 메모리에 올림 ,numpy를 np로 줄여서 사용, numpy.array는 list를 matrix처럼 생기게 바꿔준다. but matrix는 아님

In [76]:
import numpy as np
a=[(1,2,3), (3,8,0)]
print(a)
b = np.array(a)
print(b)
print(type(b))

[(1, 2, 3), (3, 8, 0)]
[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


numpy.ndarray끼리 곱연산시, 행렬곱이 아닌 원소곱 return

In [77]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


# Numpy.matrix -행렬생성

여기서 c의 type은 np.array, d의 type은 list, numpty.matrix로 행렬 생성할 때 np.array, list 둘 다 된다.

In [79]:
c = np.matrix(b)
print(c)
print(type(c))

d = np.matrix(a)
print(d)
print(type(d))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>
[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


행렬의 곱연산, 곱이 가능한 형태가 아니라 error 출력

In [32]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

# matrix Transpose

In [35]:
print(c.T)
c*c.T

[[1 3]
 [2 8]
 [3 0]]


matrix([[14, 19],
        [19, 73]])